INSERT INTO `questions` (`id`, `questionSet`, `question`, `optionA`, `returnA`, `optionB`, `returnB`, `isCount`, `isFinalCount`, `questionExplained`) VALUES
(1, 1, 'Do you understand what is requested?', 'Yes', 1, 'No', 0, 0, 0, 'More Info About The Question.'),
(2, 2, 'Can you ask the requester to elaborate further on the request?', 'Yes', 1, 'No', 0, 0, 0, 'More Info About The Question.'),
(3, 3, 'Do you understand how to perform the request?', 'Yes', 2, 'No', 0, 0, 0, 'More Info About The Question.'),
(4, 3, 'Are you capable of performing the request?', 'Yes', 2, 'No', 0, 0, 0, 'More Info About The Question.'),
(5, 3, 'Do you have the authority to perform the request?', 'Yes', 1, 'No', 0, 0, 0, 'More Info About The Question.'),
(6, 4, 'Is the requested action or information available to the public?', 'Yes', 0, 'No', 2, 0, 0, 'More Info About The Question.'),
(7, 4, 'Is this a preapproved request that can be performed in a life threatening emergency?', 'Yes', 0, 'No', 2, 0, 0, 'More Info About The Question.'),
(8, 4, 'Are there any administrative reasons for refusal?', 'Yes', 1, 'No', 2, 0, 0, 'More Info About The Question.'),
(9, 4, 'Are there any procedural reasons for refusal?', 'Yes', 1, 'No', 2, 0, 0, 'More Info About The Question.'),
(10, 4, 'Is this an unusual or new type of request?', 'Yes', 1, 'No', 2, 0, 0, 'More Info About The Question.'),
(11, 4, 'Are there any other reasons for refusal?', 'Yes', 1, 'No', 2, 0, 0, 'More Info About The Question.'),
(12, 5, 'Is the requester''s identity verifiable?', 'Yes', 3, 'No', 0, 0, 0, 'More Info About The Question.'),
(13, 5, 'Can the authority level of the requester be verified?', 'Yes', 3, 'No', 3, 1, 0, 'More Info About The Question.'),
(14, 5, 'Can the credibility of the requester be verified?', 'Yes', 3, 'No', 3, 1, 0, 'More Info About The Question.'),
(15, 5, 'Did you have a previous interaction with the requester?', 'Yes', 3, 'No', 3, 1, 0, 'More Info About The Question.'),
(16, 5, 'Are you aware of the existence of the requester?', 'Yes', -1, 'No', -1, 1, 1, 'More Info About The Question.'),
(17, 6, 'Can you verify the requester through a third party source?', 'Yes', 2, 'No', 0, 0, 0, 'More Info About The Question.'),
(18, 6, 'Does the verification process reflect the same information as verification requirements?', 'Yes', 1, 'No', 0, 0, 0, 'More Info About The Question.'),
(19, 7, 'Does the requester have the necessary authority to request the action or the information?', 'Yes', 1, 'No', 0, 0, 0, 'More Info About The Question.');
